### ISSUE TITLE
Cannot find module 'jquery'

### ISSUE THREAD

**Issue by BuZZ-dEE** [ianhattendorf/autocomplete-ruby#10]
[Enter steps to reproduce below:]
1. Install plugin
2. Open Atom

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: linux 4.7.6-1-ARCH
**Thrown From**: [autocomplete-ruby](https://github.com/ianhattendorf/autocomplete-ruby) package, v0.2.0
### Stack Trace

Failed to load the autocomplete-ruby package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/sschlatow/.atom/packages/autocomplete-ruby/lib/autocomplete-ruby-client.coffee:1:5)
    at Object.<anonymous> (/home/sschlatow/.atom/packages/autocomplete-ruby/lib/autocomplete-ruby-client.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/sschlatow/.atom/packages/autocomplete-ruby/lib/autocomplete-ruby-provider.coffee:1:16)
    at Object.<anonymous> (/home/sschlatow/.atom/packages/autocomplete-ruby/lib/autocomplete-ruby-provider.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/sschlatow/.atom/packages/autocomplete-ruby/lib/autocomplete-ruby.coffee:1:18)
    at Object.<anonymous> (/home/sschlatow/.atom/packages/autocomplete-ruby/lib/autocomplete-ruby.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:721:27)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited"
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v1.0.2 (inactive)
angularjs, v0.3.5 (inactive)
atom-arc-ui, v1.1.0 (inactive)
atom-beautify, v0.29.13 (inactive)
dojo-snippets, v1.0.0 (inactive)
atom-easy-jsdoc, v4.7.1 (inactive)
atom-ternjs, v0.15.0 (inactive)
autocomplete-java, v1.2.5 (inactive)
autocomplete-python, v1.8.6 (inactive)
autocomplete-ruby, v0.2.0 (inactive)
color-picker, v2.2.2 (inactive)
emmet, v2.4.3 (inactive)
git-blame, v0.4.11 (inactive)
git-plus, v5.18.0 (inactive)
git-time-machine, v1.5.3 (inactive)
highlight-selected, v0.11.2 (inactive)
jquery-snippets, v11.0.0 (inactive)
js-refactor, v0.7.3 (inactive)
language-fish-shell, v1.0.5 (inactive)
language-svg, v0.9.4 (inactive)
linter, v1.11.18 (inactive)
linter-csslint, v1.3.3 (inactive)
linter-javac, v1.9.4 (inactive)
linter-jshint, v3.0.1 (inactive)
linter-ruby, v1.2.2 (inactive)
minimap, v4.25.5 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
minimap-pigments, v0.2.1 (inactive)
open-file-in, v1.2.3 (inactive)
pigments, v0.37.0 (inactive)
print-atom, v0.1.1 (inactive)
project-manager, v3.2.5 (inactive)
python-debugger, v0.1.0 (inactive)
python-indent, v1.0.0 (inactive)
python-isort, v0.0.7 (inactive)
python-tools, v0.6.8 (inactive)
refactor, v0.10.0 (inactive)
remote-edit2, v3.0.0 (inactive)
split-diff, v1.0.5 (inactive)
svg-preview, v0.10.0 (inactive)
svgo, v2.6.0 (inactive)
symbols-tree-view, v0.13.2 (inactive)
term3, v0.22.1 (inactive)
uglify, v1.2.6 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by ianhattendorf** [comment]
@Mexxerio could this be from #9?

**Comment by ianhattendorf** [comment]
Looks like atom.io is affected by the DynDNS outage, once that's resolved I'll take a look.

**Comment by ianhattendorf** [comment]
I'm not seeing this error, autocomplete for ruby is working for me on a clean install:
`$ sudo pacman -Syu`
`$ sudo pacman -S atom ruby`
`$ gem install rsense`
`$ apm install autocomplete-ruby`

Could you try creating a new user and installing only this package? If that works, try installing a few of your packages at a time and see if there's a conflict?

I no longer use atom any more, so I'm not sure what else could be causing the problem.

**Comment by BuZZ-dEE** [comment]
@ianhattendorf you can close this. Now it works fine.
