### ISSUE TITLE
Failed to load the autocomplete-ruby package

### ISSUE THREAD

**Issue by lollypop27** [ianhattendorf/autocomplete-ruby#29]
[Enter steps to reproduce:]

1. Installed apm install autocomplete-ruby
2. open Atom and got the error

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [autocomplete-ruby](https://github.com/ianhattendorf/autocomplete-ruby) package 0.2.6

### Stack Trace

Failed to load the autocomplete-ruby package

```
At Command failed: gem environment
/bin/sh: 1: gem: not found


Error: Command failed: gem environment
/bin/sh: 1: gem: not found

  at checkExecSyncError (child_process.js:495:13)
  at execSync (child_process.js:535:13)
  at childProcess.(anonymous function) (ELECTRON_ASAR.js:680:22)
  at getExecPathFromGemEnv (/packages/autocomplete-ruby/lib/gem-home.coffee:6:12)
  at /packages/autocomplete-ruby/lib/gem-home.coffee:15:1)
  at /packages/autocomplete-ruby/lib/gem-home.coffee:1:1)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at /packages/autocomplete-ruby/lib/autocomplete-ruby.coffee:2:12)
  at /packages/autocomplete-ruby/lib/autocomplete-ruby.coffee:1:1)
  at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
  at /app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
  at /app.asar/src/package.js:123:28
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
  at /app.asar/src/package-manager.js:412:19
  at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
  at /app.asar/src/atom-environment.js:794:28

```

### Commands

```
     -0:23 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
aligner-scss 1.1.0 
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-ternjs 0.17.2 
atom-typescript 10.1.14 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autocomplete-ruby 0.2.6 
color-picker 2.2.5 
cucumber 0.6.0 
cucumber-autocomplete 0.7.2 
cucumber-step 0.2.0 
double-tag 0.4.0 
emmet 2.4.3 
file-icons 2.0.16 
gherkin-autocomplete 2.0.0 
git-control 0.8.2 
git-history 3.2.0 
git-plus 7.3.3 
goto-definition 1.2.0 
language-diff 0.7.0 
language-gherkin 1.0.4 
language-haml 0.24.1 
language-rspec 0.5.1 
language-slim 0.5.0 
linter 1.11.23 
linter-coffeelint 1.2.1 
linter-haml 2.0.0 
linter-hlint 0.5.0 
linter-htmlhint 1.3.2 
linter-js-yaml 1.2.7 
linter-jshint 3.0.2 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-rails-best-practices 0.2.2 
linter-rubocop 0.5.3 
linter-scss-lint 3.1.0 
linter-slim 1.0.0 
linter-write-good 0.8.0 
markdown-pdf 1.5.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
multi-cursor 2.1.5 
pigments 0.39.0 
pretty-json 1.6.1 
rails-rspec 0.3.2 
rspec 0.3.2 
sort-lines 0.14.0 
sync-settings 0.8.1 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
trailing-spaces 0.4.0 
```

**Comment by ianhattendorf** [comment]
Do you have ruby installed? Is `gem` available on the PATH?

**Comment by ianhattendorf** [comment]
Closed due to no response.

**Comment by BobHood** [comment]
As the owner didn't respond, I will. I don't have Ruby installed on this machine, and I got that error. I mirror the install of Atom and it's plugins on all the machines I have. All but one box I have, has Ruby installed (2xOSX, 2xLinux, 1xWindoze), and I only get the error on the Micro$loth Windoze box that has no Ruby.

**Comment by iehdk** [comment]
I get the same err on Windoze w/o Ruby.

**Comment by DominikAlberski** [comment]
I got that error with ruby installed via rvm on ubuntu 18.04

**Comment by SolitonBreather** [comment]
I got that error on mint 19 with ruby installed by rbenv method
