### ISSUE TITLE
Error starting rsense

### ISSUE THREAD

**Issue by robjac** [ianhattendorf/autocomplete-ruby#32]
I've updated my gems; and i'm still getting this error. 
Even after setting the `rsense` path (mine is `/Users/robjac/.rbenv/shims/rsense`

```
autocomplete-ruby: exec error: Error: Command failed: /Users/robjac/.rbenv/versions/2.3.3/bin/rsense start --port 47367 --path /Users/robjac/___masked___/___masked___
/Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate rsense-server-0.5.18, because jruby-jars-9.1.8.0 conflicts with jruby-jars (~> 1.7.4) (Gem::ConflictError)
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/lib/rsense/client/daemon.rb:4:in `<top (required)>'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:3:in `require_relative'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:3:in `<top (required)>'
	from /Users/robjac/.rbenv/versions/2.3.3/bin/rsense:22:in `load'
	from /Users/robjac/.rbenv/versions/2.3.3/bin/rsense:22:in `<main>'
(You might need to set the rsense path, see the readme)
```

Using `rbenv 1.1.0` 

I've never had this working before. I've been relying on the core implementation. `autocomplete-plus`

**Comment by ianhattendorf** [comment]
> `Unable to activate rsense-server-0.5.18, because jruby-jars-9.1.8.0 conflicts with jruby-jars (~> 1.7.4)`

This looks like an error with RSense, or possibly rbenv. Are you able to start rsense from the command line in the directory of one of your ruby projects?

**Comment by robjac** [comment]
Nope.; It actually spits out the same error 😟 : 

```
/Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate rsense-server-0.5.18, because jruby-jars-9.1.8.0 conflicts with jruby-jars (~> 1.7.4) (Gem::ConflictError)
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/lib/rsense/client/daemon.rb:4:in `<top (required)>'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:3:in `require_relative'
	from /Users/robjac/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rsense-0.5.18/bin/rsense:3:in `<top (required)>'
	from /Users/robjac/.rbenv/versions/2.3.3/bin/rsense:22:in `load'
	from /Users/robjac/.rbenv/versions/2.3.3/bin/rsense:22:in `<main>'
```

I haven't jumped back in to find the culprit; but as a Rubyist and a veteran Rails engineer, I MUST FIND A SOLUTION 😝

**Comment by ianhattendorf** [comment]
I would try uninstalling all ruby versions + rbenv, cleaning all ruby related caches (gems/dotfiles/etc.), and seeing if it works with just the system ruby. If that doesn't work, try reinstalling rbenv with just the latest ruby version, and setting that as the global default version.

If that doesn't work, then I'm out of ideas unfortunately.

**Comment by robjac** [comment]
I'll try my best to do that; but at the risk of borking my multiple local
dev stacks, may wait until the weekend. Or give up on this, as rsense is
dead. Pity, bummer, shame. :(

**Comment by ianhattendorf** [comment]
I'm going to go ahead an close this, feel free to reply if you have any updates.

**Comment by robjac** [comment]
All good! Thanks Ian.

**Comment by diramos1** [comment]
I don't know if it related with this issue, but i realized that rsense was not starting recently, so I solved uninstalling everything and install in the follow order, forcing sinatra version:
```
$ gem install sinatra:1.4.8 rsense
```
That all.

-------
My current environment:
rbenv 1.1.0-2-g4f8925a
ruby 2.4.1
