### ISSUE TITLE
Uncaught Error: kill ESRCH

### ISSUE THREAD

**Issue by liam-ngy** [ianhattendorf/autocomplete-ruby#39]
[Enter steps to reproduce:]

1. Turn off autocomplete-ruby

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [autocomplete-ruby](https://github.com/ianhattendorf/autocomplete-ruby) package 0.2.7

### Stack Trace

Uncaught Error: kill ESRCH

```
At internal/process.js:172

Error: kill ESRCH
    at exports._errnoException (util.js:1026:11)
    at process.kill (internal/process.js:172:13)
    at /packages/autocomplete-ruby/lib/autocomplete-ruby-client.coffee:89:21
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  4x -2:50.1.0 vim-mode-plus:move-down (input.hidden-input)
     -2:49.4.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -2:47 intentions:highlight (input.hidden-input)
     -2:46.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
  3x -2:45.4.0 core:backspace (input.hidden-input)
     -2:40.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -2:39.2.0 vim-mode-plus:delete (input.hidden-input)
     -2:38.7.0 vim-mode-plus:activate-linewise-visual-mode (input.hidden-input)
  4x -2:38.6.0 vim-mode-plus:move-up (input.hidden-input)
  3x -2:37.3.0 vim-mode-plus:delete (input.hidden-input)
     -2:36.2.0 core:save (input.hidden-input)
     -2:34.6.0 settings-view:open (input.hidden-input)
     -0:46.8.0 core:backspace (input.hidden-input)
     -0:46.5.0 core:confirm (input.hidden-input)
     -0:15.8.0 vim-mode-plus:move-up (input.hidden-input)
     -0:15.4.0 vim-mode-plus:move-down (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aligner 0.22.3 
aligner-ruby 1.5.0 
atom-beautify 0.29.23 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.10 
atom-terminal 0.8.0 
atom-ternjs 0.18.2 
auto-indent 0.5.0 
autocomplete-modules 1.6.9 
autocomplete-paths 1.0.5 
autocomplete-ruby 0.2.7 
busy-signal 1.4.1 
capybara-snippets 0.2.0 
cursor-history 0.10.1 
dash 1.7.1 
docblockr 0.9.4 
easy-motion-redux 1.1.1 
emmet 2.4.3 
execute-as-ruby 0.2.1 
file-icons 2.1.4 
foldername-tabs 0.2.4 
gemsource 0.3.0 
git-blame 1.0.1 
git-diff-details 1.4.0 
git-history 3.3.0 
git-plus 7.7.0 
highlight-selected 0.13.1 
history-tracker 0.1.0 
Hydrogen 1.12.1 
imdone-atom 2.2.6 
intentions 1.1.2 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
jshint 1.8.6 
language-babel 2.58.0 
language-haml 0.24.1 
language-rspec 0.6.1 
language-slim 0.5.0 
lazy-motion 0.7.0 
linter 2.1.4 
linter-coffeelint 1.2.1 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-rubocop 2.1.1 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.3 
linter-write-good 0.9.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.28.1 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
nerd-treeview 0.5.3 
nuclide 0.222.0 
open-this 0.4.0 
paner 0.4.0 
pdf-view 0.57.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
rails-finder 0.8.0 
rails-latest-migration 1.1.6 
rails-partials 0.9.2 
rails-snippets 2.15.0 
rails-transporter 1.6.5 
react 0.16.2 
recent-files-fuzzy-finder 0.3.1 
relative-numbers 0.7.1 
remember-file-positions 0.2.2 
ror-refactor 0.3.1 
ruby-block 0.3.6 
ruby-block-converter 3.5.0 
ruby-test 1.0.2 
ruby-test-switcher 1.2.3 
script 3.14.1 
sort-lines 0.14.0 
split-diff 1.3.0 
symbol-gen 1.3.1 
sync-settings 0.8.1 
todo-show 1.11.0 
toggle-packages 1.1.0 
vim-mode-plus 0.91.0 
vim-mode-plus-exchange 0.2.1 
vim-mode-plus-move-selected-text 0.10.0 
vim-mode-plus-move-to-symbols 0.3.0 
wordcount 2.10.4 
Zen 0.16.4 
zentabs 0.8.8 
```

**Comment by ianhattendorf** [comment]
What do you mean by 'turn off'? Is this disabling the plugin in the settings? I've tried disabling the plugin and wasn't able to reproduce this. Could you be a little more specific on how you're getting this to occur? Thanks.

**Comment by liam-ngy** [comment]
Yeah sure. When I just turn that plugin off. Than I got this error. That's what I can tell..I don't why I get this error everytime..

**Comment by liam-ngy** [comment]
My rsense path is .rbenv/versions/2.4.0/bin/rsense

**Comment by ianhattendorf** [comment]
Please update to v0.2.8 and let me know if that resolves it for you.

The `ESRCH` error means the rsense process wasn't found, so `process.kill` was failing. Ignoring errors from `process.kill` should resolve this, since we call `./rsense stop` as well.

**Comment by liam-ngy** [comment]
Your fix is working. Thanks for that!
