### ISSUE TITLE
can't find gem rsense

### ISSUE THREAD

**Issue by ghost** [ianhattendorf/autocomplete-ruby#45]
Using Atom v1.26.0 x64. OS X 10.11.6. Ruby 2.5.0 w/ RVM.
Not sure this is a problem with rsense _per se_, but maybe??
```
autocomplete-ruby: exec error: Error: Command failed: /Users/dude/.rvm/gems/ruby-2.5.0/bin/rsense start --port 47367 --path .
/Users/dude/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem rsense (>= 0.a) with executable rsense (Gem::GemNotFoundException)
	from /Users/dude/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
	from /Users/dude/.rvm/gems/ruby-2.5.0/bin/rsense:23:in `<main>'
	from /Users/dude/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dude/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ianhattendorf** [comment]
Without knowing your setup, the only suggestion I can make is to uninstall rvm, wipe the ~/.rvm directory, and try with the system ruby. If that works, it's probably an issue with rvm and you can troubleshoot accordingly. You could also try running rsense from the command line.

Honestly though, I'm not even sure if this works any more. It relies on rsense, which hasn't been updated in almost 4 years. I need to add a note in the readme clarifying this.
